"""empty message

Revision ID: e89eb446a59c
Revises: 
Create Date: 2025-02-09 11:06:13.034467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89eb446a59c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exchange', sa.Integer(), nullable=False, comment='是否完成兑换：0：未兑换；1：已兑换；'))
        batch_op.drop_column('is_finish')

    with op.batch_alter_table('task_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dream_score', sa.Integer(), nullable=False, comment='完成任务所获取的理想值'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_list', schema=None) as batch_op:
        batch_op.drop_column('dream_score')

    with op.batch_alter_table('item_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finish', sa.INTEGER(), nullable=False))
        batch_op.drop_column('is_exchange')

    # ### end Alembic commands ###
